### ISSUE TITLE
Code seems to be bugged

### ISSUE THREAD

**Issue by Lukasz93P** [fntneves/laravel-transactional-events#47] opened 2021-07-29 19:05 UTC
Hi, I didn't tested if it works properly but I found something weird, which seems to bu a bug.
`Neves\Events\TransactionalDispatcher::128`, theres a code like follows:
``` 
$this->currentTransaction = $this->isTransactionRunning()
            ? $this->currentTransaction->add($transactionNode)
            : $transactionNode;

        $this->currentTransaction = $transactionNode;
```

First statements assigns value to class field conditionally while statement below immediately overwrites it.

**Comment by fntneves** [comment] 2021-07-30 08:23
Hello,

The outcome of this code is the expected behavior, since the `currentTransaction` class field must always point to the most recent started transaction.

As the `$this->currentTransaction->add($transactionNode)` method call returns the parent node of the fresh started transaction, I override it at the end of the method in order to ensure it points to the new transaction.

It indeed can be refactored to something like this, since the `else´ branch is redundant:

```php
if ($this->isTransactionRunning()) {
    $this->currentTransaction->add($transactionNode)
}

$this->currentTransaction = $transactionNode;
```

I'm going to close this, since this change is not urgent nor determines the correct functioning of the library.

**Closed by fntneves** 2021-07-30 08:23 UTC
