### ISSUE TITLE
 Call to a member function getParent() on null

### ISSUE THREAD

**Issue by 4n70w4** [fntneves/laravel-transactional-events#27] opened 2019-08-26 14:20 UTC
```
Call to a member function getParent() on null {"userId":3,"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to a member function getParent() on null at /var/www/app/vendor/fntneves/laravel-transactional-events/src/Neves/Events/TransactionalDispatcher.php:229)
```

```php
            Bus::pipeThrough([UseDatabaseTransactions::class]);
//            dispatch_now($Job->chain([$Job2, $Job3, $Job4, $Job5]) );
            dispatch_now($Job);
            dispatch_now($Job2);
            dispatch_now($Job3);
            dispatch_now($Job4);
            dispatch_now($Job5);
            Bus::pipeThrough([]);

```

Failed on line `dispatch_now($Job2);
`

```php
class UseDatabaseTransactions {

    public function handle($command, $next) {
        return DB::transaction(function() use ($command, $next) {
            return $next($command);
        });
    }

}
```

```
#0 /var/www/app/vendor/fntneves/laravel-transactional-events/src/Neves/Events/TransactionalDispatcher.php(161): Neves\\Events\\TransactionalDispatcher->finishTransaction()
#1 /var/www/app/vendor/fntneves/laravel-transactional-events/src/Neves/Events/TransactionalDispatcher.php(299): Neves\\Events\\TransactionalDispatcher->onTransactionCommit()
#2 /var/www/app/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(347): Neves\\Events\\TransactionalDispatcher->Neves\\Events\\{closure}(Object(Illuminate\\Database\\Events\\TransactionCommitted))
#3 /var/www/app/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(196): Illuminate\\Events\\Dispatcher->Illuminate\\Events\\{closure}('Illuminate\\\\Data...', Array)
#4 /var/www/app/vendor/fntneves/laravel-transactional-events/src/Neves/Events/TransactionalDispatcher.php(114): Illuminate\\Events\\Dispatcher->dispatch('Illuminate\\\\Data...', Array, false)
#5 /var/www/app/vendor/laravel/framework/src/Illuminate/Database/Connection.php(813): Neves\\Events\\TransactionalDispatcher->dispatch(Object(Illuminate\\Database\\Events\\TransactionCommitted))
#6 /var/www/app/vendor/laravel/framework/src/Illuminate/Database/Concerns/ManagesTransactions.php(162): Illuminate\\Database\\Connection->fireConnectionEvent('committed')
#7 /var/www/app/vendor/laravel/framework/src/Illuminate/Database/Concerns/ManagesTransactions.php(30): Illuminate\\Database\\Connection->commit()
#8 /var/www/app/vendor/laravel/framework/src/Illuminate/Support/helpers.php(1124): Illuminate\\Database\\Connection->Illuminate\\Database\\Concerns\\{closure}(NULL)
#9 /var/www/app/vendor/laravel/framework/src/Illuminate/Database/Concerns/ManagesTransactions.php(31): tap(NULL, Object(Closure))
#10 /var/www/app/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php(349): Illuminate\\Database\\Connection->transaction(Object(Closure))
#11 /var/www/app/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(237): Illuminate\\Database\\DatabaseManager->__call('transaction', Array)
#12 /var/www/app/app/Jobs/Pipes/UseDatabaseTransactions.php(12): Illuminate\\Support\\Facades\\Facade::__callStatic('transaction', Array)
#13 /var/www/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): App\\Jobs\\Pipes\\UseDatabaseTransactions->handle(Object(App\\Jobs\\Sender), Object(Closure))
#14 /var/www/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(App\\Jobs\\Sender))
#15 /var/www/app/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(98): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#16 /var/www/app/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(413): Illuminate\\Bus\\Dispatcher->dispatchNow(Object(App\\Jobs\\Sender), false)
#17 /var/www/app/app/Nova/Actions/Signer.php(85): dispatch_now(Object(App\\Jobs\\Sender))
```

**Comment by mfn** [comment] 2019-08-30 20:59
I just had the same error during a test.

It's possible to reproduce with:
- begin
- commit
- rollback

I.e. trying to rollback after a commit reproduces this problem.

In my case this behaviour was triggered due to this code:
```php
try {
  …
  $transaction->commit();
} catch (\Throwable $t) {
  $transaction->rollback();
}
```
On of the pending events, which was dispatched once the `commit` was done, generated a PHP error (bug in code…).

This led to above `->commit()` actually also throwing an exception and then ending up trying to `rollback` => 💥 

Now, the above is my custom code.

But when I look at OPs stacktrace, I saw this line:
> `#12 /var/www/app/app/Jobs/Pipes/UseDatabaseTransactions.php(12): Illuminate\\Support\\Facades\\Facade::__callStatic('transaction', Array)`

This means it's using `\Illuminate\Database\Concerns\ManagesTransactions::transaction`:
```php
            $this->beginTransaction();

            // We'll simply execute the given callback within a try / catch block and if we
            // catch any exception we can rollback this transaction so that none of this
            // gets actually persisted to a database or stored in a permanent fashion.
            try {
                return tap($callback($this), function () {
                    $this->commit();
                });
            }

            // If we catch an exception we'll rollback this transaction and try again if we
            // are not out of attempts. If we are out of attempts we will just throw the
            // exception back out and let the developer handle an uncaught exceptions.
            catch (Exception $e) {
                $this->handleTransactionException(
                    $e, $currentAttempt, $attempts
                );
            } catch (Throwable $e) {
                $this->rollBack();

                throw $e;
            }
```
It's the same pattern: `->commit()` is in the `try` block and if a pending event dispatched right after the commit produces an exception, it's rolled back (in the above code `handleTransactionException` also performs a rollback).

**Comment by fntneves** [comment] 2019-08-31 11:51
That means that the transaction was committed and, therefore, there's no way to rollback, even if the dispatched events throw exceptions.

I need to fix it, to ignore rollbacks/commits that are made when there's no transaction running.

**Comment by mfn** [comment] 2019-08-31 13:27
Yes, I too think this case should be handled by the library.

However I wonder if maybe it's an "architecture" bug in the official `ManagesTransactions`: don't think many would expect the rollback being triggered, after a commit already happened, just because one of the events cases an exception.

**Comment by fntneves** [comment] 2019-09-04 19:15
I am not able to reproduce this with the following code:

```php
        $this->dispatcher->listen('foo', function ($payload) {
            throw new \Exception();
        });

        try {
            DB::beginTransaction();
            $this->dispatcher->dispatch('foo', 'first');
            DB::commit();
        } catch(\Exception $e) {
            DB::rollback();
        }
```

**Comment by mfn** [comment] 2019-09-04 20:16
The event `'foo'` must be a transactional event, in your case, use a config like this:
```php
    'transactional' => [
        '*',
    ],
```

**Comment by fntneves** [comment] 2019-09-04 20:17
It already is.

I am not receiving an error like this. I only get an error when I call `DB::commit()` directly, without calling `beginTransaction` first.
Even when just calling `DB::rollBack()`, I did not get this.

**Comment by mfn** [comment] 2019-09-04 20:31
> It already is.

I only can say: I simply copy pasted your code, it did not throw the error.

I changed the config as I mentioned: it immediately threw the `getParent` error.

I wonder if there might be something _in between_?

Can you push a PR with your (non failing) test case? Might help debugging this.

**Comment by fntneves** [comment] 2019-09-04 20:36
Which version are you using?

**Comment by mfn** [comment] 2019-09-04 20:38
1.8.3 with Laravel 6; but also reproduce in 1.8.2 and 5.8.something

I noticed the changing the config _within_ the test will not work for me:
```php
    public function test(): void
    {
        config(['transactional-events.transactional' => '*']);
        dump(config('transactional-events.transactional'));

        $this->dispatcher = $this->app->make(Dispatcher::class);

        $this->dispatcher->listen('foo', function ($payload) {
            throw new \Exception();
        });

        try {
            DB::beginTransaction();
            $this->dispatcher->dispatch('foo', 'first');
            DB::commit();
        } catch(\Exception $e) {
            DB::rollBack();
        }
    }
```
It really needs to be changed in the config for me (but this is in my app, not in the library project)

**Comment by fntneves** [comment] 2019-09-04 20:45
You need to use the `setTransactionalEvents` method of Dispatcher method. The dispatcher class does not access config file every single time. It loads the config at the beginning of the application execution.


```
    public function test(): void
    {
        $this->dispatcher = $this->app->make(Dispatcher::class);
        $this->dispatcher->setTransactionalEvents(['*']);

        $this->dispatcher->listen('foo', function ($payload) {
            throw new \Exception();
        });

        try {
            DB::beginTransaction();
            $this->dispatcher->dispatch('foo', 'first');
            DB::commit();
        } catch(\Exception $e) {
            DB::rollBack();
        }
    }
```

**Comment by mfn** [comment] 2019-09-04 20:52
Your (first) example from https://github.com/fntneves/laravel-transactional-events/issues/27#issuecomment-528079423 raises the error for me:
```
Error : Call to a member function getParent() on null
 /vagrant/project/vendor/fntneves/laravel-transactional-events/src/Neves/Events/TransactionalDispatcher.php:229
 /vagrant/project/vendor/fntneves/laravel-transactional-events/src/Neves/Events/TransactionalDispatcher.php:177
 /vagrant/project/vendor/fntneves/laravel-transactional-events/src/Neves/Events/TransactionalDispatcher.php:303
 /vagrant/project/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php:347
 /vagrant/project/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php:196
 /vagrant/project/vendor/fntneves/laravel-transactional-events/src/Neves/Events/TransactionalDispatcher.php:114
 /vagrant/project/vendor/laravel/framework/src/Illuminate/Database/Connection.php:815
 /vagrant/project/vendor/laravel/framework/src/Illuminate/Database/Concerns/ManagesTransactions.php:197
 /vagrant/project/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php:349
 /vagrant/project/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:237
 /vagrant/project/tests/EventTest.php:130

```

**Comment by fntneves** [comment] 2019-09-04 20:58
Damn, I'm getting confused 🤦‍♂ 

I will install a new app and check why this happens in application but not in package's test suite...

I am using sqlite under the hood. Even though I do not suspect of it has something to do with the underlying database, could you please check if the behavior depends on the underlying database?

**Comment by mfn** [comment] 2019-09-04 21:01
Hmm. I'm using postgres btw, not sqlite (also not for tests). But the DB driver shouldn't make a difference…

**Comment by mfn** [comment] 2019-09-04 21:05
Ah! I'm using the `DatabaseTransactions` trait, that must be the difference.

Bingo: tested it in the library and could reproduce it.

**Comment by fntneves** [comment] 2019-09-04 21:09
Ok, can you explain a bit more the scenario that causes this error? 😬

**Comment by mfn** [comment] 2019-09-05 06:17
Well, I'm not OP so I only "saw" this particular error in **tests**.

But I _did saw_ it because I had an error/bug/exception thrown in a Listener; so in a nutshell, the smallest reproducible sample is your example:
```php
<?php

use Orchestra\Testbench\TestCase;
use Neves\Events\EventServiceProvider;
use Neves\Testing\DatabaseTransactions;

class TransactionalDispatcherTest extends TestCase
{
    use DatabaseTransactions;
    protected $dispatcher;

    public function setUp(): void
    {
        parent::setUp();

        unset($_SERVER['__events']);

        $this->dispatcher = $this->app['events'];
        $this->dispatcher->setTransactionalEvents(['*']);
    }


    protected function getPackageProviders($app)
    {
        // Add an event listener to the previous event dispatcher.
        $app['events']->listen('previous_bound_event', function () {
            $_SERVER['__previous_listener'] = 'OK';
        });

        return [EventServiceProvider::class];
    }

    protected function getEnvironmentSetUp($app)
    {
        $app['config']->set('database.default', 'testbench');
        $app['config']->set('database.connections.testbench', [
            'driver'   => 'sqlite',
            'database' => ':memory:',
        ]);
        $app['config']->set('database.connections.other', [
            'driver'   => 'sqlite',
            'database' => ':memory:',
        ]);
    }

    public function testThrowInCommit(): void
    {
        $this->dispatcher->listen('foo', function ($payload) {
            throw new \Exception();
        });

        try {
            DB::beginTransaction();
            $this->dispatcher->dispatch('foo', 'first');
            DB::commit();
        } catch (\Exception $e) {
            DB::rollBack();
        }
    }
}
```
But maybe it's a red herring on some way, as I in particular never saw this in production yet.

**Comment by mfn** [comment] 2019-09-05 06:44
One reason I wrote https://github.com/fntneves/laravel-transactional-events/issues/27#issuecomment-526830649

The difference in tests, when handling the exception differently, is the difference between seeing the un-helpful `getParent` error _or_ the actual error; which, when debugging tests, can be the difference between day and night.

But I understand if _my_ whole case could be just an artificial scenario due to the trait?

**Comment by bytestream** [comment] 2019-09-05 20:11
The problem is with the `DatabaseTransactions` trait:
```php
$currentDispatcher = $connection->getEventDispatcher();
$connection->setEventDispatcher($emptyDispatcher);
$connection->beginTransaction();
```

It changes the event dispatcher instance which means the begin transaction event which this package is listening for never fires. 

This commit https://github.com/fntneves/laravel-transactional-events/commit/d50a13a9e27fbdbf8f1a227f0d6b02f537632137 added a dependency. The commit transaction event now relies on the begin transaction event being fired (as you'd expect).

So the immediate fix is to roll back to `v1.8.0`

**Comment by mfn** [comment] 2019-09-05 20:17
> The problem is with the `DatabaseTransactions` trait:

FTR, I just copied that method from your existing `RefreshDatabase` trait, so I'd say the same problems applies to it, too.

No need for an immediate fix for me, as I said, for me (not OP!) it so far only manifested in harder-than-necessary to debug broken tests.

**Comment by mfn** [comment] 2019-09-05 20:18
>  from your existing

Ops, sorry, didn't realize the reply is from someone else :-)

**Comment by bytestream** [comment] 2019-09-06 16:52
Just to clarify my earlier comment.

**Steps to replicate:**
1. Use `DatabaseTransactions` trait
2. Run `DB::commit()` inside a test

**Why:**
As noted in my earlier comment; `TransactionBeginning` event is expected to fire and set `currentTransaction` var. `DatabaseTransactions` trait prevents that event from firing. `DB::commit()` inside a test causes `TransactionCommitted` event to fire which expects `currentTransaction` var to be set. It's not, so error thrown.

**Fix:**
Rather than lock myself to `1.8.0` (which works), I found another approach.

Override `Illuminate\Database\Connection` and add:
```php
    /**
     * Run something without firing any connection related events.
     *
     * @param  callable $callback
     * @return mixed
     */
    public function withoutEvents(callable $callback)
    {
        $dispatcher = static::getEventDispatcher();

        static::unsetEventDispatcher();

        try {
            return $callback($this);
        } finally {
            if ($dispatcher) {
                static::setEventDispatcher($dispatcher);
            }
        }
    }
```

Add `DatabaseTransactions` trait to test class:
```php
    use Illuminate\Foundation\Testing\DatabaseTransactions;

    /**
     * Begin a database transaction on the testing database.
     *
     * @return void
     * @throws \Exception
     */
    public function beginDatabaseTransaction()
    {
        $database = $this->app->make('db');

        foreach ($this->connectionsToTransact() as $name) {
            $connection = $database->connection($name);

            $connection->withoutEvents(function ($connection) {
                $connection->beginTransaction();
            });
        }

        $this->beforeApplicationDestroyed(function () use ($database) {
            foreach ($this->connectionsToTransact() as $name) {
                $connection = $database->connection($name);

                $connection->withoutEvents(function ($connection) {
                    $connection->rollBack();
                });

                $connection->disconnect();
            }
        });
    }
```

In any test that runs `DB::commit()`:
```php
DB::withoutEvents(function (ConnectionInterface $connection) {
    $connection->commit();
});
```

Not aware of a neater way to do this using Mockery, as it would require conditionally using the mock based on the event.

**Comment by fntneves** [comment] 2019-09-07 10:45
OK, we've identified the root cause.

I have a fix in mind. I'll just ignore events when there's no registered opened transaction. Will release it soon.

**Closed** 2019-09-07 11:12 UTC

**Comment by fntneves** [comment] 2019-09-07 11:19
This is fixed now.

Thank all of you for helping in pointing the root cause of this.

Specially @4n70w4 for opening this issue, which drove to make this package better!

**Comment by mpyw** [comment] 2019-11-26 07:18
[Add DatabaseTransactions trait for transactional events by mfn · Pull Request #28 · fntneves/laravel-transactional-events](https://github.com/fntneves/laravel-transactional-events/pull/28)
