### ISSUE TITLE
How does it work in nested (emulated with savepoints) transactions?

### ISSUE THREAD

**Issue by mpyw** [fntneves/laravel-transactional-events#2] opened 2017-10-08 06:13 UTC
```php
DB::transaction(function () {
    DB::transaction(function () {
       event(new TransactionalEvent());
    });
    // A: dispatched here?
});
// B: or here?
```

**Comment by mpyw** [comment] 2017-10-08 06:29
I guess that this package does not change behavior of `DB` facades.
Do I always need to begin/commit/rollback via dispatcher?

**Comment by fntneves** [comment] 2017-10-08 10:18
Hi @mpyw,

Before anything else, thank you for creating this issue.

In fact, this package does not change the behavior of the `DB` facade. It relies on emitted events from Laravel Core according to `beginTransaction`, `rollback` and `commit` states.

When you have nested transactions (or savepoints), events are dispatched at the point `A`. As I never needed this particular situation in my projects, I did not consider this on this package.

Nonetheless, this is a relevant issue and I already did a brainstorm on how to do this while developing this package, to match this request.

I can do it soon, are you interested?

**Comment by fntneves** [comment] 2017-10-08 10:54
Hi @mpyw,

Before anything else, thank you for creating this issue.

There is a difference between `event` and `dispatch` helpers. The first one aims to raise an event to its listeners, which `handle` implementation can be sent to a queue. The latter does not trigger listeners and executes the `handle` implementation. Laravel handle these two situation differently. The first is handled by the `events` facade, while the second is handled by the `Dispatcher` class provided by the Container. Sincerely, I do not know if it is on purpose or not.

This package associates the transactional layer to the `events` key to be resolved by the Container. Therefore, as `dispatch` directly requires the Dispatcher class, it will not use the transactional layer.

Therefore, this transactional layer acts only on the `event` helper. The `dispatch` method uses the original dispatcher class to dispatch the event. 

Answering to your question:

In fact, this package does not change the behavior of the `DB` facade. It relies on emitted events from Laravel Core, specifically `beginTransaction`, `rollback` and `commit`.

When you have nested transactions (or savepoints), events raised using `dispatch` will be immediately handled at the point they are dispatcher. In turn, events using `event` are dispatched only at the point `A`, if a transaction succeeds. This happens because Laravel dispatches a "commited" event on a transaction's commit.

IMO, it is the expected behavior, since save points guarantees that data is persistent.

This, however, started a relevant issue related to the applicability of this transactional layer also to the `dispatch` helper.

What do you think?

Edit: I am going to make it clear in documentation.

**Comment by mpyw** [comment] 2017-10-08 21:00
Thank you for replying.

> events raised using dispatch will be immediately handled at the point they are dispatcher.

I need to delay publishing events until **ALL** transactions are done. So I wrote a new package taking a different approach.

[mpyw/laravel-transaction-observer: Observe delayed events and fire them after ALL transactions are done.](https://github.com/mpyw/laravel-transaction-observer)

**Comment by fntneves** [comment] 2017-10-08 22:08
You're welcome.

Maybe I didn't get your point. Why do you need to publish events only when all transactions succeed, if you have savepoints that guarantee database's changes are effectively persisted?

The purpose of this package is to prevent taking actions (i.e. sending e-mails) relying on data that is not guaranteed to succeed. Having savepoints, I believe that events can be raised, otherwise savepoints are useless, no?

If I am misunderstanding your point, can you provide a concrete use case?

**Comment by mpyw** [comment] 2017-10-08 22:16
Oh, maybe I'm misunderstanding Laravel transaction emulations...

```php
// Works
DB::transaction(function () {
    DB::transaction(function () {
        DB::transaction(function () {
        });
    });
});

// Does not work
DB::transaction(function () {
    DB::transaction(function () {
    });
    DB::transaction(function () {
    });
});
```

Right?

**Comment by fntneves** [comment] 2017-10-08 22:54
Both approaches work in Laravel. It just depends on your use case.
The second approach seems more legit to me to leverage save points.
However, I am thinking about use cases for nested transactions, which are very particular.

Just digged into Laravel's code and realized that savepoints are not effectively persisted when any of them rolls back, unless you catch the exception. It means that data is loss if an uncaught  exception is raised on any inner transaction or even on the outer transaction.

Thus, let's break this into some subjects of discussion:

- Wouldn't it be the same as having a single `DB::transaction(...)` statement? A single exception breaks every savepoint and finally the outer transaction, i.e. leading Laravel to call `rollback` until the start point of the outer transaction.

- Why do you need nested transactions? I do not see any reason here since you are not leveraging savepoints. If you don't, then this package fits your purpose, for the reason I've stated above.

- When you are leveraging savepoints, raising events when a "sub-transaction" commits may be correct or not, depends on the use case. At this point, I am convinced that my package should consider this (as I have mentioned, it is a very small change and I will add this, or you can contribute to this repo).

Sorry for the long messages, but this is a very interesting topic 😄

**Comment by mpyw** [comment] 2017-10-09 08:33
> If I am misunderstanding your point, can you provide a concrete use case?

Yeah, this is what I wanted to describe. See the following example.

[mpyw/laravel-delayed-counter-cache: Delayed counter cache incremented/decremented out of transactions](https://github.com/mpyw/laravel-delayed-counter-cache)

```php
/**
 * BEGIN
 *
 *   INSERT post()
 *
 *   SAVEPOINT 01
 *   INSERT comment(post_id) VALUES (1) // This increment will be rejected.
 *   ROLLBACK TO SAVEPOINT 01
 *
 *   SAVEPOINT 02
 *   INSERT comment(post_id) VALUES (1) // Once this increment will be accepted, but finally rejected.
 *
 *   SAVEPOINT 03
 *   INSERT comment(post_id) VALUES (1) // This increment will be rejected.
 *   ROLLBACK TO SAVEPOINT 03
 *
 * ROLLBACK
 * // All increments should be rejected.
 */

try {
    DB::transaction(function () use (&$post) {
        $post = Post::create();

        try {
            DB::transaction(function () use ($post) {
                $comment = new Comment();
                $comment->post()->associate($post);
                $comment->save(); // This increment will be rejected.
                throw new \UnexpectedValueException('Oops!');
            });
        } catch (\UnexpectedValueException $e) { }
    
        DB::transaction(function () use ($post) {
            $comment = new Comment();
            $comment->post()->associate($post);
            $comment->save(); // Once this increment will be accepted, but finally rejected.
        });
    
        try {
            DB::transaction(function () use ($post) {
                $comment = new Comment();
                $comment->post()->associate($post);
                $comment->save(); // This increment will be rejected.
                throw new \UnexpectedValueException('Oops!');
            });
        } catch (\UnexpectedValueException $e) { }
    });
} catch (\UnexpectedValueException $e) { }

// All increments should be rejected.
```

Savepoint can be rejected.

**Comment by mpyw** [comment] 2017-10-09 11:11
Important thing: 

[MySQL :: MySQL 5.6 Reference Manual :: 13.3.4 SAVEPOINT, ROLLBACK TO SAVEPOINT, and RELEASE SAVEPOINT Syntax](https://dev.mysql.com/doc/refman/5.6/en/savepoint.html)

> All savepoints of the current transaction are deleted if you execute a COMMIT, or a ROLLBACK that does not name a savepoint.

It think it means that savepoint does not guarantee the activities before.

**Comment by fntneves** [comment] 2017-10-10 21:17
Yes, you're right.

I've added support for nested transactions on 1.1.0.

However, I am still not convinced that nested transactions are usual and even practical.
Once a nested transaction is not able to commit and it does not abort the whole transaction, then it could be a signal that it could be enqueued for later processing. It is only my opinion, by the way, I am sure you have a great use case on your projects, and if that's the case, I want to let you know that I added support for nested transactions.

Just a note, I looked into your tests and I liked your approach, using testbench. I got rid of mocks and use testing helpers from that package. I've learned few things, from this issue!

Thanks for your discussion. 👍

**Closed by fntneves** 2017-10-10 21:17 UTC
Labels: question

**Comment by KieronWiltshire** [comment] 2021-02-15 02:25
This is actually something I really need. My code sometimes calls other codes which nest themselves in transactions by default. Is this something we can look on adding, I will even submit a PR myself if you prefer?

**Comment by mfn** [comment] 2021-02-15 11:07
I'm using this package and nesting so far worked for me (using Postgres)

Is there maybe a specific problem you experience? Best to create a new issue IMHO.

**Comment by KieronWiltshire** [comment] 2021-02-15 14:04
> I'm using this package and nesting so far worked for me (using Postgres)
> 
> Is there maybe a specific problem you experience? Best to create a new issue IMHO.

Yeah I’ve done so now.
